// ════════════════════════════════════════════════════════════════════
// SCRIPORA — FEEDBACK LIBRARY v3.0
// ════════════════════════════════════════════════════════════════════
//
// ARCHITECTURE
// Three layers:
//   1. UNIVERSAL ENGINE — FB.hook / ctx / body / cta / out
//      Applies to every script. 25-30 variants per component.
//   2. TYPE PROFILES — FB.types
//      Type-specific overrides: 7 existing + 5 new (12 total)
//   3. STATS + PATTERNS — FB.stats / FB.patterns
//
// NEW TYPES ADDED v3.0:
//   - Reaction / Commentary
//   - Deep Dive / Analysis
//   - Challenge / Experiment
//   - Case Study
//   - Educational / Explainer
//
// ════════════════════════════════════════════════════════════════════

var FB = {};

// ─────────────────────────────────────────────────────────────────
// UNIVERSAL HOOK — 30 variants
// ─────────────────────────────────────────────────────────────────

FB.hook = {
  noTension: {
    level: 'high',
    observation: [
      'This hook makes a statement but does not create a question in the viewer\'s mind.',
      'The opening declares something without leaving anything unresolved.',
      'There is no open loop here — the sentence completes itself before the viewer has a reason to continue.',
      'The hook announces rather than provokes.',
      'The opening tells the viewer something without making them need to know more.',
      'This sentence closes itself. Nothing is left unresolved for the viewer to stay for.',
      'The hook introduces an idea and immediately satisfies it, removing the pull.',
      'A statement without a question gives the viewer permission to stop watching.',
      'The opening is informative but not compelling — it tells rather than hooks.',
      'The first sentence delivers its payload immediately, leaving nothing for the viewer to wait for.',
      'This hook states a fact where it should pose a problem.',
      'The opening explains what the video is about instead of making the viewer need it.',
      'There is no cognitive gap here — the viewer processes the sentence and feels finished.',
      'The hook resolves before it opens. The viewer has nothing to stay for.',
      'This is a title dressed as a hook. It announces the topic without creating a need.',
      'The opening gives information when it should create curiosity.',
      'The viewer who reads this sentence has no reason to read the next one.',
      'A completed thought in the opening is a closed door. The viewer has nowhere to go.',
      'This hook explains what the viewer will learn instead of making them need to learn it.',
      'The first sentence tells the viewer what is coming. The mystery is gone before it began.',
      'There is no tension here — the hook is a conclusion without a setup.',
      'The opening is a summary of what follows, which removes the reason to follow.',
      'This hook functions as a table of contents rather than a provocation.',
      'The first sentence could be the last sentence of the video. That is structurally wrong.',
      'A statement without an unresolved edge lets the viewer disengage immediately.',
      'The hook is a declaration of intent, not a reason to care.',
      'Information without implication does not hold attention.',
      'This opening is safe, which means it is forgettable.',
      'The hook tells the viewer what to think instead of making them want to find out.',
      'A hook that does not create a question is a hook that does not hook.'
    ],
    consequence: [
      'Without an unresolved question, the viewer has no psychological pull toward the next sentence.',
      'A statement that completes itself removes the reason to keep watching.',
      'Attention is held by tension, and this opening creates none.',
      'The viewer can process this sentence and feel finished, which is the opposite of what a hook should do.',
      'When the opening resolves itself, the viewer has no unfinished business with the video.',
      'A hook without tension is a title, not an entry point. The viewer has no reason to stay.',
      'The first sentence should create a debt. This one does not.',
      'Viewers who feel complete after the first sentence will not stay for the second.',
      'Without forward momentum in the hook, the context section has to do double work.',
      'The psychological pull that keeps a viewer past the first ten seconds requires an unresolved idea. This hook does not provide one.',
      'The viewer who is not curious about what comes next will scroll to what comes next.',
      'A statement without an unanswered question allows the viewer to decide the video is not for them.',
      'The hook is the only sentence some viewers will read. This one does not earn the next.',
      'Without a gap to bridge, the viewer has no investment in the content.',
      'The opening tells the viewer what they will get, which removes the need to watch to find out.',
      'A hook that does not hook has cost the video its most valuable seconds.',
      'The viewer who feels no curiosity at the opening will feel no loss when they leave.',
      'This hook asks nothing of the viewer, so the viewer gives nothing back.',
      'The opening treats the viewer as a consumer of information rather than a participant in discovery.',
      'Without tension, the only reason to continue is patience — and patience is in short supply.',
      'The first sentence establishes no stakes, so the viewer has no reason to care.',
      'A hook without an unresolved question is a button that does nothing when pressed.',
      'The viewer who is not intrigued has already decided to leave; they are just waiting for the first pause.',
      'This opening creates no emotional investment, which means the viewer is already neutral.',
      'Neutral viewers become gone viewers at the first distraction.',
      'The hook does the opposite of its job: it satisfies before the viewer is invested.',
      'A hook that resolves early steals from the body section\'s ability to deliver.',
      'The viewer who has nothing to wait for will wait for nothing.',
      'This opening closes the door it was meant to open.',
      'The hook is a period where it should be a comma.'
    ],
    direction: [
      'Rewrite the first sentence as a direct question or a bold claim that demands verification.',
      'Introduce an idea that is surprising enough to make the viewer want to know more.',
      'End the hook on something unresolved — a promise, a contradiction, or a provocative half-statement.',
      'Create a gap between what the viewer knows and what the script is about to tell them.',
      'Replace the statement with a question that puts the viewer in the scenario.',
      'Make a claim that the viewer will want to test against their own experience.',
      'Turn the statement into a prediction: "Most people get this completely wrong."',
      'Open with the consequence of not knowing the information, not the information itself.',
      'Ask the viewer to imagine a specific scenario that makes the topic personally relevant.',
      'Lead with the most surprising or counterintuitive thing your script reveals.',
      'Start with a problem the viewer already feels, not a solution you are offering.',
      'Create a gap: "Here is what everyone believes. Here is why they are wrong."',
      'End the first sentence with a colon or dash — something that demands completion.',
      'Ask a question the viewer cannot answer confidently.',
      'Make a claim that sounds wrong — the viewer will stay to see if you can prove it.',
      'Open with a consequence: "If you keep doing this, you are going to lose viewers."',
      'Start with a specific, relatable scenario that forces the viewer to see themselves in it.',
      'Use the word "you" in the first sentence to make it personal.',
      'Create a mystery: "There is one thing almost every creator gets wrong in their first ten seconds."',
      'Make the first sentence a half-sentence that demands completion.',
      'Open with a statistic that challenges assumptions.',
      'Start with a confession: "I made a mistake that cost me 10,000 views."',
      'Use contrast: "What I thought would work — and what actually worked."',
      'Begin with a moment of tension: "I almost deleted this video three times."',
      'Open with the viewer\'s frustration: "You have been doing this wrong the whole time."',
      'Start with a promise: "By the end of this, you will know exactly what to change."',
      'Use a rhetorical question that the viewer has already asked themselves.',
      'Open with a contradiction: "The thing that helped me grow was the thing I was avoiding."',
      'Create urgency: "This is the last time I am explaining this."',
      'Make the first sentence the most provocative thing in the entire script.'
    ]
  },
  creatorFirst: {
    level: 'mid',
    observation: [
      'This hook opens with the creator before it opens with the viewer.',
      'The first word positions you at the centre of the opening, not the person watching.',
      'The hook leads with your experience before it leads with their problem.',
      'You introduce yourself before you introduce a reason to care.',
      'The opening is about the creator\'s journey, not the viewer\'s situation.',
      'The script begins in the creator\'s world before earning the right to take the viewer there.',
      'Opening with "I" or "my" places the creator\'s story ahead of the viewer\'s need.',
      'The first sentence is autobiographical where it should be viewer-facing.',
      'The hook establishes the creator as the subject before the viewer has a reason to care.',
      'Personal narrative in the opening is a tool for the context section, not the hook.',
      'The opening answers "who are you?" before answering "why should I care?"',
      'The first sentence makes the video about the creator, which is the opposite of what a hook should do.',
      'The viewer is introduced to you before they are introduced to their own problem.',
      'This hook assumes the viewer already cares about the creator. That is rarely true.',
      'The opening asks for trust before it has earned it.',
      'The first word is about you. The first word should be about them.',
      'The hook is a biography where it should be a provocation.',
      'The viewer who does not know you has no reason to care about your story.',
      'The opening positions you as the subject, which makes the viewer a spectator.',
      'This hook tells the viewer what you have done instead of what they can gain.',
      'The first sentence is a credential without context, which lands as self-promotion.',
      'The opening is a story about the creator waiting to be made relevant to the viewer.',
      'The hook asks the viewer to invest in you before you have invested in them.',
      'The first word is "I" when it should be "you" or a problem statement.',
      'The opening is personal when it should be universal.',
      'This hook signals that the video is a creator diary rather than a viewer resource.',
      'The viewer came for themselves. The opening gives them you instead.',
      'The hook establishes your experience without establishing its value to the viewer.',
      'The first sentence is about your journey. The viewer is not on that journey yet.',
      'This opening makes the viewer work to find themselves in the content.'
    ],
    consequence: [
      'A viewer who does not yet trust you has no reason to process your credentials in the first sentence.',
      'When the opening is about you, the viewer has to decide whether to care about you before they decide whether to care about the topic.',
      'Viewers who do not know you will not invest attention in your story until you have given them a reason to.',
      'The psychological pull that keeps a viewer watching comes from their own problem, not from yours.',
      'Creator-first openings require the viewer to extend trust before it has been earned.',
      'Most viewers who see a creator-first hook will decide in the first three seconds whether they care about that creator. Most will not.',
      'An opening that begins with the creator\'s experience delays the moment the viewer sees themselves in the content.',
      'The viewer came for themselves, not for you. A creator-first hook makes them wait for relevance.',
      'When the hook is about the creator, the viewer is a spectator rather than a participant from the first sentence.',
      'Creator-first openings work only for creators the viewer already knows. For everyone else, they are a barrier.',
      'The viewer who does not know you will not give you the benefit of the doubt.',
      'A creator-first opening asks the viewer to extend empathy before receiving value.',
      'The most common reaction to a creator-first hook is: "Why should I care?"',
      'If the viewer does not answer that question in their favor, they leave.',
      'The opening is about your story, but the viewer is the protagonist of their own attention.',
      'A creator-first hook converts fewer viewers than a viewer-first hook. This is measurable.',
      'The viewer who sees "I" in the first sentence assumes the video is self-indulgent.',
      'That assumption is hard to reverse even if the rest of the video is viewer-focused.',
      'The opening sets the frame. A creator-first frame puts the viewer at a distance.',
      'Viewers who feel at a distance watch less attentively and leave earlier.',
      'The hook is the only chance to make the viewer the protagonist. This hook does not take it.',
      'A creator-first opening works against the trust-building function of the context section.',
      'The viewer starts skeptical rather than open, which means everything after must overcome that.',
      'The opening is a speed bump for the viewer, not a ramp.',
      'Viewers who encounter a creator-first hook are more likely to describe the video as "about the creator" rather than "about the topic."',
      'That framing reduces the video\'s utility in the viewer\'s memory.',
      'A creator-first hook signals inexperience to experienced viewers.',
      'The viewer who sees a personal opening assumes the content is anecdotal rather than researched.',
      'This opening requires the viewer to extend curiosity about you before you have earned it.',
      'Most viewers will not. They will scroll.'
    ],
    direction: [
      'Rewrite the first sentence so it names something the viewer already feels, fears, or wants.',
      'Replace the opening "I" with "You" or a direct question about the viewer\'s situation.',
      'Lead with the problem before you introduce the person who solved it.',
      'Open with a claim or a question that forces the viewer to measure it against their own experience.',
      'Move the personal story to the context section where it works as a credential.',
      'Start with the viewer\'s situation: "If you have ever tried to..." instead of "I tried to..."',
      'Ask yourself: what does the viewer want from this video? Open with that.',
      'The creator\'s story is powerful context. It is not a hook. Move it down and open with the viewer.',
      'Replace the first sentence entirely with a question the viewer would ask themselves.',
      'Make the viewer the subject of the first sentence. Every word should be about them, not you.',
      'The first word should be "you", "if", "what", "why", or "how" — not "I" or "my".',
      'Open with a problem statement: "Most creators make this mistake in their first ten seconds."',
      'Use a universal scenario: "You are losing viewers before you even start talking."',
      'Create a viewer-centric frame: "Here is what nobody tells you about..."',
      'Start with the viewer\'s frustration: "You have been trying to grow your channel, but nothing is working."',
      'Open with a question the viewer is already asking: "Why do some videos blow up and others flop?"',
      'Lead with a benefit: "Here is how to double your retention in the first 30 seconds."',
      'Use the viewer\'s own words: "You have probably heard that hooks matter. Here is what they actually mean."',
      'Make the first sentence about the viewer\'s outcome: "What you are about to learn will change how you write scripts forever."',
      'Open with a specific viewer scenario: "You have spent hours on a script only to watch viewers leave in the first minute."',
      'The hook is not your introduction. It is the viewer\'s invitation.',
      'Treat the first sentence as the answer to: "What does the viewer need to hear right now?"',
      'If you would not say the first sentence to a stranger in an elevator, rewrite it.',
      'The viewer should see themselves in the first sentence. If they do not, you have failed.',
      'Make the hook feel like the viewer\'s own thought, not your introduction.',
      'Use "you" in the first sentence. It is the most powerful word for attention.',
      'Start with a consequence: "If you are not hooking viewers in the first sentence, you are wasting the rest of your script."',
      'Open with a contradiction: "The thing you think is keeping viewers is actually pushing them away."',
      'Make the first sentence something the viewer wants to argue with.',
      'The hook is for them. The context is for you. Keep them separate.'
    ]
  },
  selfResolving: {
    level: 'high',
    observation: [
      'This hook raises a question and then answers it in the same breath.',
      'The tension is created and collapsed within the same sentence.',
      'The opening introduces curiosity and immediately satisfies it.',
      'The hook poses a problem and resolves it before the viewer has time to feel it.',
      'Curiosity is opened and closed in the same moment, leaving nothing for the viewer to stay for.',
      'The first sentence does all the work — it creates the pull and destroys it.',
      'The hook functions as a complete thought where it should be an incomplete one.',
      'The opening creates a gap and immediately fills it, removing the viewer\'s reason to continue.',
      'Both the question and the answer appear in the hook, leaving the body with nothing to deliver.',
      'The resolution comes too early. The viewer receives the payoff before they have invested any attention.',
      'The hook is a full paragraph where a sentence would be enough — and that sentence resolves itself.',
      'The opening answers the question it raises, which means the viewer has nothing to wait for.',
      'The first sentence is a closed loop when it should be an open one.',
      'The hook does not trust the viewer to wait, so it gives them everything immediately.',
      'This is a micro-version of the entire video: problem, solution, done.',
      'The hook is a complete argument, which makes the rest of the script feel like repetition.',
      'The opening gives the conclusion before the evidence, which undercuts the evidence.',
      'The hook is a spoiler for its own content.',
      'The first sentence contains both the setup and the punchline, which leaves nothing for the body.',
      'The tension is created and released before the viewer has time to feel it.',
      'The hook functions as a summary rather than an invitation.',
      'The opening is efficient in a way that undermines its purpose.',
      'The viewer receives the answer before they feel the question.',
      'The hook does not create curiosity — it satisfies curiosity that has not yet been created.',
      'The first sentence answers the question the viewer would have asked if they had been given time to ask it.',
      'The opening collapses the curiosity loop before it is fully formed.',
      'The hook is a self-contained unit that does not require the rest of the video.',
      'The first sentence could stand alone, which means it should not be the first sentence.',
      'The resolution comes so fast that the viewer does not have time to become invested.',
      'This hook is the whole video compressed into a sentence, which means the video is redundant.'
    ],
    consequence: [
      'Curiosity that is immediately resolved gives the viewer no reason to stay for what comes next.',
      'When the hook answers its own question, the psychological pull disappears at the exact moment it should be strongest.',
      'A viewer who already has the answer will not stay for the explanation.',
      'Resolving the tension in the hook trades the viewer\'s attention for a moment of clarity they did not need yet.',
      'The open loop is the most powerful retention tool in a YouTube script. Closing it in the hook removes it entirely.',
      'Viewers who feel the video has already told them the main thing will leave before the good content begins.',
      'A self-resolving hook converts potential long-term viewers into ten-second viewers.',
      'The body section has nothing to deliver to a viewer who already received the point in the hook.',
      'Early resolution is the structural equivalent of giving away the ending in the trailer.',
      'The viewer\'s commitment to the video is built on unresolved tension. This hook removes that commitment immediately.',
      'The viewer who gets the answer in the hook has no reason to trust that the rest will be different.',
      'A self-resolving hook trains the viewer that they do not need to watch the whole video.',
      'That training applies to future videos as well.',
      'The hook satisfies the viewer\'s curiosity before they have invested anything, which means they feel no loss if they leave.',
      'The cost of leaving is zero because they already got the answer.',
      'This hook reduces the perceived value of the body section.',
      'The body section is now explaining something the viewer already knows.',
      'Viewers who already know the answer are harder to keep engaged.',
      'The hook has done the body\'s job, so the body has to find a new job.',
      'Most bodies are not structured for a new job. They were built to deliver on the hook.',
      'This structural mismatch creates a video that feels like it is repeating itself.',
      'The viewer who senses repetition will leave.',
      'A self-resolving hook is one of the most common reasons for high early drop-off.',
      'The viewer who leaves in the first thirty seconds because the hook resolved itself will never know what the body contained.',
      'The hook wasted the most valuable seconds of the video.',
      'The creator who uses self-resolving hooks consistently trains viewers to leave early.',
      'That training is hard to undo.',
      'The hook is the only part of the video every viewer sees. If it self-resolves, every viewer gets a worse experience.',
      'This is a structural failure that affects every viewer who starts the video.',
      'The cost of a self-resolving hook is not small. It is the cost of most of your potential audience.'
    ],
    direction: [
      'Keep the question open. Let the answer live later in the script.',
      'Split the hook into the problem and move the resolution to the end of the context section.',
      'Create a bigger question from the answer — let the revelation generate more curiosity, not less.',
      'If you must tease the answer, make it incomplete enough that the viewer still needs the full explanation.',
      'Cut everything after the first comma or semicolon and see if the hook is stronger without the resolution.',
      'The hook should end with the viewer leaning forward, not sitting back.',
      'Identify which half of the hook is the question and which is the answer. Delete the answer.',
      'Replace the resolution with a consequence: not the answer, but why not having the answer matters.',
      'Turn the completed thought into a half-thought: "Most creators never figure this out — " and stop there.',
      'The hook is a debt the rest of the script repays. Do not repay it in the first sentence.',
      'End the hook on a word that demands completion: "because", "but", "however".',
      'Use a dash or ellipsis to indicate there is more coming.',
      'If your hook has two sentences, delete the second one and see if the first is stronger.',
      'Move the answer to the end of the context or the beginning of the body.',
      'Let the viewer sit with the question through the context section.',
      'The longer the question is unresolved, the stronger the pull to keep watching.',
      'Make the resolution feel earned by delaying it.',
      'The hook should raise the stakes of not knowing, not lower them.',
      'Ask yourself: what is the smallest amount I can say to create the largest question?',
      'Say only that. Nothing more.',
      'The hook is a question mark. The body is the answer.',
      'If you put the answer in the hook, you have no question.',
      'Think of the hook as the first panel of a comic strip. It should make you want to see the second panel.',
      'If the first panel contains the whole story, there is no reason to look at the second.',
      'Trust the viewer to wait. They will wait if you give them a reason to.',
      'The reason to wait is the unresolved question you planted.',
      'If you resolve it immediately, you have removed the reason to wait.',
      'The hook is not a summary. It is an invitation.',
      'Treat the hook as a promise, not a delivery.',
      'Promises keep viewers. Deliveries let them go.'
    ]
  }
};
